// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4NPJB51ndb1iZDhOHAp2i-qTLu0fru8o',
    appId: '1:591986343837:web:b9fdcd0e024f83c4b8f974',
    messagingSenderId: '591986343837',
    projectId: 'bloc-todo-ec7bf',
    authDomain: 'bloc-todo-ec7bf.firebaseapp.com',
    storageBucket: 'bloc-todo-ec7bf.appspot.com',
    measurementId: 'G-TF434RJ1VN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAbjhDYBSUoSliHdKuWl2TWvTFB-hbqHY',
    appId: '1:591986343837:android:1184303923337d66b8f974',
    messagingSenderId: '591986343837',
    projectId: 'bloc-todo-ec7bf',
    storageBucket: 'bloc-todo-ec7bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqdVnvEn8QvcpnN4O5M6jwb1s0H5T4ueI',
    appId: '1:591986343837:ios:df4a4e68d26752a8b8f974',
    messagingSenderId: '591986343837',
    projectId: 'bloc-todo-ec7bf',
    storageBucket: 'bloc-todo-ec7bf.appspot.com',
    iosClientId: '591986343837-hbc396p9nb22lkb5o0lar28n7o4k8s8f.apps.googleusercontent.com',
    iosBundleId: 'com.example.blocToDoApp',
  );
}
